### ISSUE TITLE
MqttClient can't work on dotnet core

### ISSUE THREAD

**Issue by ZeekoZhu** [Gravicode/GnatMQCore#1]
On the dotnet core platform, the `MqttClient` always throws a `MqttCommunicationException` when I trying to connect to a broker.

I think it is because of these code [MqttClient.cs#L1383-L1392](https://github.com/Gravicode/GnatMQCore/blob/master/GnatMQ.Core/GnatMQ.Core/MqttClient.cs#L1383-L1392)

Fom the MQTT specification, when broker received a CONNECT message, it should return a CONNACK, so the `MqttClientException` shouldn't be thrown.

**Comment by mifmasterz** [comment]
![image](https://user-images.githubusercontent.com/15245579/27900155-60967d02-6257-11e7-8fd5-2dcade43beb9.png)
I don't have any problem.. the test client in the project only runs on windows, but you can create your own client on linux by using .net core, or other languages

**Comment by ZeekoZhu** [comment]
@mifmasterz I think you should create a Console App (.Net Core), then you should find the problem

**Comment by mifmasterz** [comment]
![image](https://user-images.githubusercontent.com/15245579/27900710-a3b11c08-6259-11e7-89f7-0eb10a5b59aa.png)

ok, I have tried with .net core console app, no problem at all, please download the .net core client project from https://1drv.ms/u/s!AlCWPI4OHYZJgvwGeJud4gfaSbjSWw

**Comment by ZeekoZhu** [comment]
Yes, you are right, your broker doesn't have any problem, I use the wrong `MqttClient` defined in the `uPLibrary.Networking.M2Mqtt`.I should use this [client](https://www.nuget.org/packages/M2MqttDotnetCore/) like you.

**Comment by mifmasterz** [comment]
Ok good, so I can close this issue...
